/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelreservation;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Sandusha
 */
public class CancelReservation extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form CancelReservation
     */
    public CancelReservation() {
        try
        {
           DBConnection obj=new DBConnection();
           con=obj.GetConnection();
            
        }
        catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Error Connecting to Database"+ex,"Cancel Reservation Form",
                    JOptionPane.ERROR_MESSAGE);
                } 
        initComponents();
        txtEmail.setEditable(false);
        txtName.setEditable(false);
        txtNic.setEditable(false);
        txtPhone.setEditable(false);
        txtRnumber.setEditable(false);
        
        
    }
public void updatereservations()
{String id= txtRid.getText();
    try
        {
            PreparedStatement stmt1=con.prepareStatement
            ("Update CheckIns set Status='Cancelled' where RID='"+id+"'");
             stmt1.execute();
        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Error encountered while deleting data in the database"+ex,
                "Check Out Form",JOptionPane.ERROR_MESSAGE);
        }
}
 public void reset()
{txtRid.setText("");
txtName.setText("");
txtNic.setText("");
txtPhone.setText("");
txtEmail.setText("");
txtRnumber.setText("");
txtRid.setEditable(true);
}     


public void updaterooms()
{String rn= txtRnumber.getText();
    try
        {
            PreparedStatement stmt2=con.prepareStatement
            ("update Rooms set Status='Not Booked' where RoomNumber='"+rn+"'");
             stmt2.execute();
        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Error encountered while Updating data in the database"+ex,
                "Check Out Form",JOptionPane.ERROR_MESSAGE);
        }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtRid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtRnumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cancel Reservations");
        setMaximumSize(new java.awt.Dimension(900, 660));
        setMinimumSize(new java.awt.Dimension(900, 660));
        setPreferredSize(new java.awt.Dimension(900, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 230, 130, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("NIC");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(280, 270, 28, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 310, 110, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 350, 50, 17);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(430, 350, 160, 30);
        getContentPane().add(txtPhone);
        txtPhone.setBounds(430, 310, 160, 30);

        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        getContentPane().add(txtNic);
        txtNic.setBounds(430, 270, 160, 30);
        getContentPane().add(txtName);
        txtName.setBounds(430, 230, 160, 30);
        getContentPane().add(txtRid);
        txtRid.setBounds(330, 150, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("RID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 150, 41, 30);

        btnSearch.setFont(btnSearch.getFont().deriveFont(btnSearch.getFont().getStyle() | java.awt.Font.BOLD));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (2).png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(450, 150, 130, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Room Number");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(280, 390, 110, 17);
        getContentPane().add(txtRnumber);
        txtRnumber.setBounds(430, 390, 160, 30);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormatFactoryicons8-save-close-48 (1).png"))); // NOI18N
        btnSave.setText("Cancel");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(290, 460, 111, 50);

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormatFactoryicons8-clear-symbol-48.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setMaximumSize(new java.awt.Dimension(133, 41));
        btnClear.setMinimumSize(new java.awt.Dimension(133, 41));
        btnClear.setPreferredSize(new java.awt.Dimension(133, 41));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(440, 460, 120, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel2.setText("Cancel Reservations");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 20, 400, 40);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bG1.jpg"))); // NOI18N
        BG.setText("sdsd");
        getContentPane().add(BG);
        BG.setBounds(0, 0, 940, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String id=txtRid.getText();
        try
        {
            PreparedStatement stmt=con.prepareStatement("select Name,NIC,Mobile,Email,RoomNumber from CheckIns where RID='"+id+"' AND Status='In'");
            ResultSet rs=stmt.executeQuery();

            if(rs.next())
            {

                txtRid.setEditable(false);
                txtName.setText(rs.getString("Name"));
                txtNic.setText(rs.getString("NIC"));
                txtPhone.setText(rs.getString("Mobile"));
                txtEmail.setText(rs.getString("Email"));
                txtRnumber.setText(rs.getString("RoomNumber"));
             }
            else
            {
                JOptionPane.showMessageDialog(null,"Reservasion doesn't exist");

            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Error encountered while searching data in the database"+ex,
                "Cancel Reservation Form",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String rid=txtRid.getText();
        String name=txtName.getText();
        String Email=txtEmail.getText();
        String phone=txtPhone.getText();
        String RNmbr=txtRnumber.getText();
        String Nic=txtNic.getText();

        boolean valid=true;
        if(txtRid.getText().isEmpty()||txtName.getText().isEmpty()||txtNic.getText().isEmpty()||txtPhone.getText().isEmpty()||txtEmail.getText().isEmpty()||txtRnumber.getText().isEmpty())
            
            
        {
            JOptionPane.showMessageDialog(null,"Fields can't be blank", "Cancel Reservation Form", JOptionPane.ERROR_MESSAGE);
            valid=false;
        }
        else
        {
            if(valid)
            {
                try
                {
                    PreparedStatement stmt=con.prepareStatement("Insert into CancelledReservations values (?,?,?,?,?,?)");
                    stmt.setString(1,rid);
                    stmt.setString(2,name);
                    stmt.setString(3,Nic);
                    stmt.setString(4,phone);
                    stmt.setString(5,Email);
                    stmt.setString(6,RNmbr);
                    

                    int rows=stmt.executeUpdate();

                    if(rows>0)
                    {
                        JOptionPane.showMessageDialog(null,"Reservation Cancelled.");
                       updaterooms();
                       updatereservations();
                       reset();
                        }
                    }

                    catch(SQLException ex)
                    {
                        ex.printStackTrace();
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null,ex);
                    }

                }}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtRid.setEditable(true);
        reset();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRid;
    private javax.swing.JTextField txtRnumber;
    // End of variables declaration//GEN-END:variables
}
