/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelreservation;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Sandusha
 */
public class Login extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form Login
     */
    public Login() {
       try
        {
           DBConnection obj=new DBConnection();
           con=obj.GetConnection();
            
        }
        catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Error Connecting to Database"+ex,"Account Manage Form",
                    JOptionPane.ERROR_MESSAGE);
                }
  initComponents();
    }
     
  /**
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtUname = new javax.swing.JTextField();
        txtPw = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Villa Nilnara HMS");
        setResizable(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUname.setPreferredSize(new java.awt.Dimension(126, 22));
        jPanel5.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 190, 30));
        jPanel5.add(txtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 190, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("LOGIN");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Username");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 80, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Password");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 80, 10));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lgin.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel5.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 150, 50));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 710, 360));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/screen.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1290, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    boolean valid=true;
    if(txtUname.getText().isEmpty()|| txtPw.getPassword().length==0) 
    { JOptionPane.showMessageDialog(null,"Fields can't be blank", "Login Form", JOptionPane.ERROR_MESSAGE);
            valid=false;
    }else 
        try
        {
            String UserType= null;
            PreparedStatement stmtLogin=con.prepareStatement("select * from Users where UserID=? and Password=?");
            stmtLogin.setString(1, txtUname.getText());
            stmtLogin.setString(2,txtPw.getText());
            
            ResultSet rs=stmtLogin.executeQuery();
            
            if(rs.next())
            {
                UserType=rs.getString("UserType");
                
                   if(UserType.equals("Receptionist"))
                {
                   JOptionPane.showMessageDialog(null, "Login as Receptionist");
                    ReceptionMenu obj = new ReceptionMenu();
                    obj.show();
                    this.dispose();
                }
                
                if(UserType.equals("Accountant"))
                {
                    JOptionPane.showMessageDialog(null,"Login as Accountant");
                    AccountantMenu obj = new AccountantMenu();
                    obj.show();
                    this.dispose();
                }
                
                if(UserType.equals("FOM"))
                {
                   JOptionPane.showMessageDialog(null, "Login as  Front office Manager");
                    FomMenu obj = new FomMenu();
                    obj.show();
                    this.dispose();
                }
                
                   if(UserType.equals("Housekeeper"))
                {
                   JOptionPane.showMessageDialog(null, "Login as  HouseKeeper");
                    HkMenu obj = new HkMenu();  
                    obj.show();
                    this.dispose();
                }
                       if(UserType.equals("F&B Manager"))
                {
                   JOptionPane.showMessageDialog(null, "Login as  F&B Manager");
                    FnbMenu obj = new FnbMenu();
                    obj.show();
                    this.dispose();
                }
                                if(UserType.equals("Chef"))
                {
                   JOptionPane.showMessageDialog(null, "Login as  Executive Chef");
                    ChefMenu obj = new ChefMenu();
                    obj.show();
                    this.dispose();
                }
         
            }
                else
                {
                    JOptionPane.showMessageDialog(null, "Password or Username is incorrect.Try Again!","Login Form", JOptionPane.ERROR_MESSAGE);
                     txtPw.setText(""); 
                     txtUname.setText("");
                }
            
        }
        
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error Logging in"+e,"User Login",JOptionPane.ERROR_MESSAGE);
        }
        
    
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
