/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelreservation;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandusha
 */
public class ManageRoom extends javax.swing.JFrame {
    Connection con;
    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() 
    { try
        {
           DBConnection obj=new DBConnection();
           con=obj.GetConnection();
            
        }
        catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Error Connecting to Database"+ex,"Manage Room Form",
                    JOptionPane.ERROR_MESSAGE);
                }
        initComponents();
    }
public void reset()
{txtRnumber.setText("");
txtPrice.setText("");
cmbBed.setSelectedItem("");
cmbRtype.setSelectedItem("");}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRnumber = new javax.swing.JTextField();
        cmbRtype = new javax.swing.JComboBox();
        cmbBed = new javax.swing.JComboBox();
        txtPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Room");
        setMaximumSize(new java.awt.Dimension(1130, 570));
        setMinimumSize(new java.awt.Dimension(1130, 570));
        setPreferredSize(new java.awt.Dimension(1130, 570));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 450));

        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Type", "Bed", "Price", "Status"
            }
        ));
        tblRooms.setToolTipText("");
        jScrollPane1.setViewportView(tblRooms);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 490, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Room Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bed");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        getContentPane().add(txtRnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 220, 30));

        cmbRtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Superior", "Deluxe" }));
        cmbRtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRtypeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbRtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 220, 30));

        cmbBed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Triple", " " }));
        getContentPane().add(cmbBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 219, 30));
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 219, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormatFactoryicons8-clear-symbol-48.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 110, 39));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormatFactoryicons8-save-close-48 (1).png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 399, 120, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel5.setText("Manage Room");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormatFactoryicons8-save-close-48 (1).png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 120, 39));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (2).png"))); // NOI18N
        jButton4.setText("Search");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 116, 40));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bG1.jpg"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void update () {
             try
            
        {
         tblRooms.setModel(new DefaultTableModel(null,new String[]{"Room_Number","Type","Bed","Price","Status"})) ;
        
            PreparedStatement stmt = con.prepareStatement("select * from Rooms");
            ResultSet rs=stmt.executeQuery();
            while (rs.next())
            {
               String Room_Number = String.valueOf(rs.getString("RoomNumber"));
                String Type = String.valueOf(rs.getString("RoomType"));
                String Bed = String.valueOf(rs.getString("Bed"));
                String Price = String.valueOf(rs.getString("Price"));
                String Status = String.valueOf(rs.getString("Status"));
                String tbData[] = {Room_Number,Type,Bed,Price,Status}; // array for saving data
                DefaultTableModel tbModel = (DefaultTableModel)tblRooms.getModel();

                tbModel.addRow(tbData);
            
        }
        }
        catch(Exception ex){
            {
                JOptionPane.showMessageDialog(null, "Error Connecting to Database"+ex,"View Stocks Form",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
             
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
     boolean valid=true;
     String roomNo= txtRnumber.getText();
     String roomtype=(String)cmbRtype.getSelectedItem();
     String bed=(String)cmbBed.getSelectedItem();
     String price=txtPrice.getText();
     
      if(txtPrice.getText().isEmpty()||txtRnumber.getText().isEmpty()||cmbRtype.getSelectedItem().toString().isEmpty()||cmbRtype.getSelectedItem().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Fields can't be blank", "Manage Room Form", JOptionPane.ERROR_MESSAGE);
            valid=false;
        }
      

              
     if(valid)
            {
                try
                {
                   PreparedStatement stat=con.prepareStatement("Insert into Rooms values ('"+roomNo+"','"+roomtype+"','"+bed+"','"+price+"','Not Booked')");
                    int rows=stat.executeUpdate();
            
            if(rows>0)
            {
                JOptionPane.showMessageDialog(null,"Room details have been saved");
                update (); 
            }
          
        }
        
        catch(Exception ex)
        {
          JOptionPane.showMessageDialog(null,"Room Exists",
                  "Room Manage Form",JOptionPane.ERROR_MESSAGE);
        } 
        
            }
              
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      update (); 
              
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbRtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRtypeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

             boolean valid=true;

     
      if(txtPrice.getText().isEmpty()||txtRnumber.getText().isEmpty()||cmbRtype.getSelectedItem().toString().isEmpty()||cmbRtype.getSelectedItem().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Fields can't be blank", "Manage Room Form", JOptionPane.ERROR_MESSAGE);
            valid=false;
        }
     if(valid)
           
        try
        {
            PreparedStatement stat=con.prepareStatement("Update Rooms set RoomType=?, Bed=?, Price=? where RoomNumber=?");

            
            stat.setString(1,(String)cmbRtype.getSelectedItem());
            stat.setString(2,(String)cmbBed.getSelectedItem());
            stat.setString(3,txtPrice.getText());
            stat.setString(4,txtRnumber.getText());

            int rows=stat.executeUpdate();
            if(rows>0)
            {
                JOptionPane.showMessageDialog(null,"Room Updated..");
                update (); 
            }

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Room not Updated Successully:"+ex,"Manage Room Form",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
                          try
        {

            PreparedStatement stmt=con.prepareStatement("Select roomNumber,RoomType,Bed,Price  from Rooms where RoomNumber=?");

            stmt.setString(1,txtRnumber.getText());

            ResultSet rs=stmt.executeQuery();

            if(rs.next())
            {
              
                txtRnumber.setText(rs.getString("roomNumber"));
                cmbRtype.setSelectedItem(rs.getString("RoomType")); 
                cmbBed.setSelectedItem(rs.getString("Bed")); 
                txtPrice.setText(rs.getString("Price"));
    
                
                JOptionPane.showMessageDialog(null,"Room Found");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Room not Found.");
            }
        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Error Encounted while searching:"+ex,"Room Form",JOptionPane.ERROR_MESSAGE);
        }
                          
                          
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg1;
    private javax.swing.JComboBox cmbBed;
    private javax.swing.JComboBox cmbRtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRnumber;
    // End of variables declaration//GEN-END:variables
}
