/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelreservation;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandusha
 */
public class ManageUsers extends javax.swing.JFrame {
    Connection con;
    /**
     * Creates new form ManageRoom
     */
    public ManageUsers() 
    { try
        {
           DBConnection obj=new DBConnection();
           con=obj.GetConnection();
            
        }
        catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Error Connecting to Database"+ex,"Manage Room Form",
                    JOptionPane.ERROR_MESSAGE);
                }
        initComponents();
    }
public void reset()
{txtId.setText("");
cmbUser.setSelectedItem("");
txtPassword.setText("");
txtConfirmPassword.setText("");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbUser = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage User Accounts");
        setMinimumSize(new java.awt.Dimension(1130, 570));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("UserType");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormatFactoryicons8-clear-symbol-48.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 110, 39));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormatFactoryicons8-save-close-48 (1).png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 120, 39));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel5.setText("Manage User accounts");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 219, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        cmbUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Receptionist", "FOM", "Chef", "F&B manager", "Accountant", "Housekeeper" }));
        getContentPane().add(cmbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 220, 30));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FormatFactoryicons8-save-close-48 (1).png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 120, 39));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (2).png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 116, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Confirm Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));
        getContentPane().add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 220, 30));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 220, 30));

        bg1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bG1.jpg"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       boolean valid=true;
        if(txtId.getText().isEmpty()||txtPassword.getText().isEmpty()||cmbUser.getSelectedItem().toString().isEmpty()||txtConfirmPassword.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Fields can't be blank", "Manage User Form", JOptionPane.ERROR_MESSAGE);
            valid=false;
        }
      else
        {
            if(txtPassword.getText().toString().length()<7)
            {
                JOptionPane.showMessageDialog(null, "Password must have more than 6 characters", "Manage User Form",
                        JOptionPane.ERROR_MESSAGE);
                valid=false;
            }
             else if(!txtPassword.getText().equals(txtConfirmPassword.getText()))
            {
                JOptionPane.showMessageDialog(null, "Password and confirm password should match","Account Manage Form",JOptionPane.ERROR_MESSAGE);
                valid=false;
            }
     if(valid)
                   try
        {
            PreparedStatement stat=con.prepareStatement("Update Users set Password=?, UserType=? where UserID=?");

            
            
            stat.setString(1,(String)txtPassword.getText());
            stat.setString(2,(String)cmbUser.getSelectedItem());
            stat.setString(3,txtId.getText());
            
          
          
            

            int rows=stat.executeUpdate();
            if(rows>0)
            {
                JOptionPane.showMessageDialog(null,"Data Updated..");
            }

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Data not Updated Successully:"+ex,"Users Form",JOptionPane.ERROR_MESSAGE);
        }
              
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
      
      
    }//GEN-LAST:event_formComponentShown

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
     reset();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     boolean valid=true;
     String UserId= txtId.getText();
     String password=txtPassword.getText();
     String usertype=(String)cmbUser.getSelectedItem();

     
      if(txtId.getText().isEmpty()||txtPassword.getText().isEmpty()||cmbUser.getSelectedItem().toString().isEmpty()||txtConfirmPassword.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Fields can't be blank", "Manage User Form", JOptionPane.ERROR_MESSAGE);
            valid=false;
        }
      else
        {
            if(txtPassword.getText().toString().length()<7)
            {
                JOptionPane.showMessageDialog(null, "Password must have more than 6 characters", "Manage User Form",
                        JOptionPane.ERROR_MESSAGE);
                valid=false;
            }
             else if(!txtPassword.getText().equals(txtConfirmPassword.getText()))
            {
                JOptionPane.showMessageDialog(null, "Password and confirm password should match","Account Manage Form",JOptionPane.ERROR_MESSAGE);
                valid=false;
            }
     if(valid)
            {
                try
                {
                   PreparedStatement stat=con.prepareStatement("Insert into Users values ('"+UserId+"','"+password+"','"+usertype+"')");
                    int rows=stat.executeUpdate();
            
            if(rows>0)
            {
                JOptionPane.showMessageDialog(null,"User details have been saved");
            }
          
        }
        
        catch(Exception ex)
        {
          JOptionPane.showMessageDialog(null,"Error",
                  "Room Manage Form",JOptionPane.ERROR_MESSAGE);
        }

            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        try
        {

            PreparedStatement stmt=con.prepareStatement("Select * from Users where UserID=?");

            stmt.setString(1,txtId.getText());

            ResultSet rs=stmt.executeQuery();

            if(rs.next())
            {

                txtId.setText(rs.getString("UserID"));
                txtPassword.setText(rs.getString("Password"));                
                cmbUser.setSelectedItem(rs.getString("UserType"));



                JOptionPane.showMessageDialog(null,"User Found");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"User not Found.");
            }
        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Error Encounted while searching:"+ex,"User Form",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
