/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotelreservation;
import java.awt.Desktop;
import java.io.File;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Sandusha
 */
public class ViewBills extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form ViewBills
     */
    public ViewBills() { try
        {
           DBConnection obj=new DBConnection();
           con=obj.GetConnection();
            
        }
        catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null, "Error Connecting to Database"+ex,"View Bills Form",
                    JOptionPane.ERROR_MESSAGE);
                } 
        initComponents();
        SimpleDateFormat dateForm = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal=Calendar.getInstance();
        txtcout.setText(dateForm.format(cal.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcout = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Bills");
        setMinimumSize(new java.awt.Dimension(1275, 718));
        setPreferredSize(new java.awt.Dimension(1275, 718));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel2.setText("View Bills");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 20, 180, 41);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Check Out Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 110, 130, 30);
        getContentPane().add(txtcout);
        txtcout.setBounds(250, 110, 180, 30);

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search (2).png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch);
        btnsearch.setBounds(470, 110, 130, 30);

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RID", "Customer Name", "NIC", "Mobile", "Email", "Check In", "Check Out", "Room Number", "Days Stayed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMain);
        if (tblMain.getColumnModel().getColumnCount() > 0) {
            tblMain.getColumnModel().getColumn(0).setResizable(false);
            tblMain.getColumnModel().getColumn(1).setResizable(false);
            tblMain.getColumnModel().getColumn(2).setResizable(false);
            tblMain.getColumnModel().getColumn(3).setResizable(false);
            tblMain.getColumnModel().getColumn(4).setResizable(false);
            tblMain.getColumnModel().getColumn(5).setResizable(false);
            tblMain.getColumnModel().getColumn(6).setResizable(false);
            tblMain.getColumnModel().getColumn(7).setResizable(false);
            tblMain.getColumnModel().getColumn(8).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 1230, 450);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setText(" Click On Reservation ID to Open the Bill");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(720, 110, 390, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bG1.jpg"))); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(1275, 718));
        bg.setMinimumSize(new java.awt.Dimension(1275, 718));
        bg.setPreferredSize(new java.awt.Dimension(1275, 718));
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
     
      try
       {
           String date=txtcout.getText();
          tblMain.setModel(new DefaultTableModel(null,new String[]{"RID","Customer_Name","NIC","Phone","Email","CheckIn","CheckOut","RoomNumber","DaysStayed"})) ;
           PreparedStatement stmt = con.prepareStatement("select * from CheckOuts where CheckOut='"+date+"'");
            ResultSet rs=stmt.executeQuery();
            DefaultTableModel tbmodel=(DefaultTableModel)tblMain.getModel();
             tbmodel.setRowCount(0);
            while (rs.next())
            {
                String RID = String.valueOf(rs.getString(1));
                String Name = String.valueOf(rs.getString(2));
                String NIC = String.valueOf(rs.getString(3));
                String Mobile = String.valueOf(rs.getString(4));
                String Email = String.valueOf(rs.getString(5));
                String CheckIn = String.valueOf(rs.getString(6));
                String CheckOut = String.valueOf((date));
                String RoomNumber = String.valueOf(rs.getString(8));
                String DaysStayed = String.valueOf(rs.getString(11));
                String tbData[] = {RID,Name,NIC,Mobile,Email,CheckIn,CheckOut,RoomNumber,DaysStayed}; 
                DefaultTableModel tbModel = (DefaultTableModel)tblMain.getModel();

                tbModel.addRow(tbData);
            
        }
        }
        catch(Exception ex){
            {
                JOptionPane.showMessageDialog(null, "Error Connecting to Database"+ex,"Check out Form",
                    JOptionPane.ERROR_MESSAGE);
                    
            }
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void tblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainMouseClicked
        int ind=tblMain.getSelectedRow();
        TableModel model=tblMain.getModel();
        String rid=model.getValueAt(ind,0).toString();
        try
        {
        if((new File("D:\\"+rid+".pdf")).exists())
        {
            Process P=Runtime
            .getRuntime()
             .exec("rundll32 url.dll.FileProtocolHandler D:\\"+rid+".pdf");
            Desktop.getDesktop().open(new File("D:\\"+rid+".pdf"));
        }
        else
        {
        JOptionPane.showMessageDialog(null, "File does not exists");
        }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, e);}
        
    }//GEN-LAST:event_tblMainMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMain;
    private javax.swing.JTextField txtcout;
    // End of variables declaration//GEN-END:variables
}
